# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'LotteryForecaster' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for LotteryForecaster

  pod 'RxSwift'
  pod 'RxCocoa'
  pod 'ReactorKit'
  pod 'SnapKit'
  pod 'Then'
  pod 'AcknowList'
  pod 'Firebase/Analytics'
  pod 'Firebase/RemoteConfig'
end
